### ISSUE TITLE
[5.1] Soft deleted records are getting fetched.

### ISSUE THREAD

**Issue by neowill2013** [laravel/framework#10115]
deleted_at column is set when I delete a record and trashed() is returning true for soft deleted record. But when I get the result it contains soft deleted records.

  Controller: index() function
```
  public function index()
    {

        $articles = Article::latest()->get();

        return view( 'articles/view_articles' )->with( [
            'articles'    => $articles
        ] );
    }
```

Model:
```
<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use SoftDeletes;

    protected $fillable = [ 'name', 'url', 'description', 'status'];

    public $dates = [ 'deleted_at' ];

}
```

Migration:
```
 Schema::create( 'articles', function ( Blueprint $table ) {
            $table->mediumInteger( 'id', true, true );
            $table->string( 'name', 500 );
            $table->string( 'url', 500 );
            $table->text( 'description' );
            $table->timestamps();
            $table->softDeletes();
            $table->enum( 'status', [ 'Y', 'N', 'D' ] )->default( 'N' );
}
```

**Comment by GrahamCampbell** [comment]
Duplicate.

**Comment by mikevrind** [comment]
If this issue is an duplicate, where is the other issue? I'm experiencing the exact same problem as @neowill2013

**Comment by sestolk** [comment]
+1 on this

**Comment by eckenroed** [comment]
+1 on this

**Comment by mikevrind** [comment]
I just fixed the issue in our project.

Our models where extending an base model (which extends the Eloquent model). The base model has his own constructor, which didn't call the parent constructor.
So adding parent::__construct(); solved our problem.

**Comment by calmdev** [comment]
I just wasted any hour to realize it was a similar oversight as described by @mikevrind. Except in my case I was overriding the model's `boot` method without calling `parent::boot();`

**Comment by neowill2013** [comment]
Still not fixed

**Comment by mikevrind** [comment]
This is not a bug, there is a possible cause of this issue in this thread.

**Comment by pranavgawri** [comment]
The fix or the correct way described by @mikevrind  worked perfectly. 
I had overridden boot and didn't call parent::boot(), so I was still getting the deleted rows, though deleted at was set. Once I called parent::boot() in the boot method it worked perfectly fine. 

But I fail to understand the reason behind, when deleted_at was set without calling parent::boot() then what else is needed, can @mikevrind please explain. (sorry if its a novice question)

Thanks

**Comment by mikevrind** [comment]
Just dig in the code of the boot method to find out what is does once fired (and does't do when not fired ;) ).
