### ISSUE TITLE
`Cache::get()` can't be mocked

### ISSUE THREAD

**Issue by tillkruss** [laravel/framework#10803]
**Issue #9729 and #10480 have been closed without fix or explanation.**

The code example from the official "Testing" docs not work: http://laravel.com/docs/5.1/testing#mocking-facades

Either the official docs need to be updated, or the `Cache` facade adjusted to make it work.
```
Cache::shouldReceive('get')
   ->once()
   ->with('key')
   ->andReturn('value');
```
Throws:
```
InvalidArgumentException: get() cannot be mocked as it a protected method and mocking protected methods is not allowed for this mock
```

**Comment by GrahamCampbell** [comment]
That's because you don't need to mock the get method on the cache repository, because there isn't one to mock.

**Comment by GrahamCampbell** [comment]
Yes, the docs are totally wrong here, sorry. We're open to PRs though. :)

**Comment by GrahamCampbell** [comment]
> Issue #9729 and #10480 have been closed without fix or explanation.

Well that's totally untrue.

I added a reason straight away.

> You can't mock a manager class like that I'm afraid. The get call there is a __callStatic followed by a __call. You can only mock facades if the next call from __callStatic is a real method.

**Comment by taylorotwell** [comment]
I've fixed this in laravel/framework by instructing mockery to allow mocking protected methods on the Facade base class. Fix should be released on next tag.

**Comment by tillkruss** [comment]
Thanks! :+1:

**Comment by apsdsm** [comment]
Was just hitting this problem - thanks for fixing :)

**Comment by J-Katzen** [comment]
Using laravel 5.2 and still having issues with Mockery Cache: 
`BadMethodCallException: Method Mockery_1_Illuminate_Cache_CacheManager::put() does not exist on this mock object`

**Comment by tillkruss** [comment]
That's a different error message.

**Comment by priyanshuchhazed** [comment]
I'm facing the same issue `Using laravel 5.2 and still having issues with Mockery Cache:
BadMethodCallException: Method Mockery_1_Illuminate_Cache_CacheManager::put() does not exist on this mock object`. Is there a fix for it?

**Comment by GrahamCampbell** [comment]
It's not a bug as such, it's because you're being naive with the mocking. The cache manager is only a proxy, so you can't mock methods that you think exist, because they don't. You'll need to mock the `__call` method, or, mock the underlying "cache repository instance".

**Comment by richartkeil** [comment]
To provide a quick solution for the described problem of @priyanshuchhazed (even if it's not issue related):

In a normal Unit test mocking through `Cache::shouldReceive('...')` works perfectly fine.

However if you write an integration test faking an HTTP request you need to condition the mock like this:
```
$cacheDriver = app('cache')->driver();
Cache::shouldReceive('driver')->andReturn($cacheDriver);
```

**Comment by sergsoares** [comment]
> To provide a quick solution for the described problem of @priyanshuchhazed (even if it's not issue related and quite some time ago):
> 
> In a normal Unit test mocking through `Cache::shouldReceive('...')` works perfectly fine.
> 
> However if you write an integration test faking an HTTP request you need to condition the mock like this:
> 
> ```
> $cacheDriver = app('cache')->driver();
> Cache::shouldReceive('driver')->andReturn($cacheDriver);
> ```

Work perfectyl for me. Thanks

**Comment by hettiger** [comment]
> It's not a bug as such, it's because you're being naive with the mocking. The cache manager is only a proxy, so you can't mock methods that you think exist, because they don't. You'll need to mock the `__call` method, or, mock the underlying "cache repository instance".

Here's what I've came up with reading your comment:

```php
// arrange
$cacheRepository = Cache::driver();
$cacheRepositorySpy = Mockery::spy($cacheRepository);
Cache::swap($cacheRepositorySpy);

// act
$this->post(/* … */);

// assert
$cacheRepositorySpy->shouldHaveReceived('has');
$cacheRepositorySpy->shouldHaveReceived('get');
```

Maybe this is helpful for others that come across this issue…

Actually it seems to be working just fine. I'm wondering if it would be a good idea to make Cache::spy() return the equivalent of my `$cacheRepositorySpy` from the example above.

It took me hours to figure this out. Documentation and / or API clearly needs an improvement to be honest.

**Comment by hettiger** [comment]
Somehow I keep coming back to this and I'm always happy that I left this comment for others and future self. 😄
