### ISSUE TITLE
[5.5] Testing Anonymous Notifications

### ISSUE THREAD

**Issue by Aferz** [laravel/framework#21347]
- Laravel Version: 5.5.1
- PHP Version: 7.1
- Database Driver & Version: Mysql 5.7

### Description:
Testing anonymous notifications is not possible so far. Laravel is making some assumptions when checking sent notifications.

### Steps To Reproduce:
Create a controller/command that simply send an anonymous notification:

```php
Notification::route('mail', 'fake@fake.org')->notify(new TestNotification);
```

Create a test:

```php
Notification::fake();

// Stuff that make the notification to be triggered

Notification::assertSentTo('fake@fake.org', 'App\Notifications\TestNotification');
```

It fails with this error:

```
YourTestClass::your_test_method
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Illuminate\Notifications\AnonymousNotifiable::getKey()
```

This error is caused in `Illuminate\Support\Testing\Fakes\NotificationFake`, line `179`:

```php
...

$this->notifications[get_class($notifiable)][$notifiable->getKey()][get_class($notification)][]

...
```

The notifiable method call `$notifiable->getKey()` is causing that every notifiable that doesn't implement that method simply fails, including `Illuminate\Notifications\AnonymousNotifiable`. There isn't an interface for notifiables, that's why I think that Laravel is making some assumptions.

For what I understand, `Illuminate\Notifications\Notifiable` trait can be attached to any entity, but in order to be tested, that entity must implement `getKey` method.

If I'm wrong, just leave the solution and I would close this issue.

Cheers.

**Comment by sebdesign** [comment]
I think this has been addressed in #20965.

**Comment by Aferz** [comment]
Mhh not really. I've seen two problems yet:

**Don't really know how to test an anonymous notification yet**

Adding `getKey()` method to the class avoids the exception. Good. But how I'm supposed to test without a "real" notifiable? Maybe this?:

```php
$anonymNotifiable = (new AnonymousNotifiable)->route('mail', 'fake@fake.org');

Notification::assertSentTo($anonymNotifiable, 'TestNotification');
```
I suggest to add this 2 methods to `NotificationFake` class to get better experience:

```php
public function assertAnonymouslySentTo($channel, $route, $notification, $callback = null)
{
    $notifiable = (new AnonymousNotifiable)->route($channel, $route);
        
    $this->assertSentTo($notifiable, $notification, $callback = null);
}

public function assertAnonymouslyNotSentTo($channel, $route, $notification, $callback = null)
{
    $notifiable = (new AnonymousNotifiable)->route($channel, $route);
        
    $this->assertNotSentTo($notifiable, $notification, $callback = null);
}
```

**Testing multiple assertions**

Despite this works good with a **single** assertion, It doesn't play well when asserting multiple anonymous notifications in the same test. If I try to test this:

```php
$anonymNotifiable = (new AnonymousNotifiable)->route('mail', '123@fake.org');
$anonymNotifiable2 = (new AnonymousNotifiable)->route('mail', '456@fake.org');

Notification::assertSentTo($anonymNotifiable, 'TestNotification');
Notification::assertNotSentTo($anonymNotifiable2, 'TestNotification');
```

The second assertion fails because the `AnonymousNotification` class returns `null` from its `getKey()` method, so both notifications are classified under the same notifiable key in `NotificationFake` class. Here:

https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Testing/Fakes/NotificationFake.php#L143
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Testing/Fakes/NotificationFake.php#L144
https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Testing/Fakes/NotificationFake.php#L178

I'd like to provide a PR, but I don't really know what `getKey()` method should return. Maybe a combination of channels w/ routes?

Suggestions ?

**Comment by sebdesign** [comment]
As a matter of fact, I ran into the exact same issue two days ago.
In your description you are using v5.5.1, but the PR I mentioned was merged in 5.5.2.

Other than that, I haven't found a way to test anonymous notifications.
The issue is that the notifiables are not being really "stored" in the NotificationFake. Only their key  (via `getKey`) is used to matche with the sent notifications.
But so there is no way to perform assertions on the notifiable objects.

One solution would be to `json_encode` the `routes` array of the anonymous notifiable. I think that could work!

**Comment by Aferz** [comment]
I upgraded to Laravel 5.5.12 once you commented about the PR and It fixed the `getKey` exception, but It didn't fix the problem that I mentioned in my last comment.

**Comment by sebdesign** [comment]
Another solution would be to add the notifiable instance along with the `notification` and the `channels` keys on the `sendNow` method. That way, we could do assertions about the anonymous user in the callback.

**Comment by Aferz** [comment]
@sebdesign This could be a nice approach. I'd like to get dedicated methods for anonymous functions as I mentioned few messages above:

```php
public function assertAnonymouslySentTo($notification, $callback = null)
public function assertAnonymouslyNotSentTo($notification, $callback = null)
```

in which the new `AnonymousNotifiable` is silently instantiated.

Nice solution! Let's see what @themsaid or @taylorotwell think.

**Comment by themsaid** [comment]
Addressed in https://github.com/laravel/framework/pull/21379
