### ISSUE TITLE
[BUG][5.5] assertViewHas, assertViewIs and asserViewMissing are not supported if you use the directive @include in your templates

### ISSUE THREAD

**Issue by joseraul** [laravel/framework#23072]
- Laravel Version: 5.5.32
- PHP Version: 7.1.9
- Database Driver & Version: N/A

### Description:
When using any of the following testing asserts:

`assertViewHas`
`assertViewIs`
`assertViewMissing`

The tests fails because of:

> The response is not a view.

If you are using the directive `@include` in your blade templates.

**Extra data**

Looks like that the view is compiled/rendered early when you use the `@include` directive. I have been checking the assert methods, and all of them are using
```
protected function ensureResponseHasView()
{
    if (! isset($this->original) || ! $this->original instanceof View) {
        return PHPUnit::fail('The response is not a view.');
    }

    return $this;
}
```
So, when I'm using the directive `@include`, `$this->original` is a raw string, otherwise is an object. I will be happy to help/fix this if someone points me to the correct direction :)

### Steps To Reproduce:
Create a simple template with the `@include` directive:

*home.blade.php*
```
<div>@include('test')</div>
```
*test.blade.php*
```
foo
```
Create a test with any of the asserts above:
```
$response = $this->get('/');
$response->assertViewHas('xx');
```
It will return:

> The response is not a view.

When obviously it should be a view object.

**Comment by themsaid** [comment]
Can't replicate this, work fine for me.

**Comment by joseraul** [comment]
Uops! thanks for your reply, let's see if I can find what has my environment that causes this strange behaviour.

**Comment by joseraul** [comment]
Yep, the problem is **laravelcollective/html**. This issue does not belongs to here :) I close it, sorry and thanks!

**Comment by mikerogne** [comment]
@joseraul What's the actual issue? Is there a way to resolve it without removing laravelcollective/html?

**Comment by joseraul** [comment]
Hey @mikerogne !

The problem was that in the test I was sending fake data to the template -obviously- BUT was not correctly formatted to be processed by the form component. This component was sending an exception that I could not see during testing, I was seeing the 'the response is not a view' -of course, it was not receiving a view, it was receiving that exception-.

So, if you are having similar problems... maybe you are doing similar mistakes: try to format the fake data correctly to be processed by the form components.

Cheers

**Comment by mikerogne** [comment]
@joseraul Thanks for following up with me! Much appreciated.

I managed to solve my own problem earlier thankfully :) In case someone else googles this problem & runs into this thread, I'll share my experience too: I'm using Laravel Debugbar, and it was injecting the debugbar code into response... which converted the actual "View" object instance response into plain HTML markup... hence it really wasn't a view, it was just a string.

Edited config/debugbar.php - disabled injecting it & problem was solved (only disables if running in console).

**Comment by iraklisg** [comment]
@mikerogne Thank you for your comment. I am too using *Laravel Debugbar* but setting `inject` property equal to `false` in the `config/debugbar.php` did not do the trick for me :cry: 

I am still getting the annoying `The response is not a view.` error message if I try to test a view that contains the `@extends` blade directive. If I remove the directive and use plain html in my `view`, then the test is passing green. 

Moreover, if I use the `@extends` directive and try to `var_dump` the `$response->original` I get an empty string as a result, but if I use plain html I get a `View` object

I also tried to complete remove *Laravel Debugbar* but the problem remains... :confused:

**Comment by cbloss** [comment]
I don't know if this will help anyone, but I'm using Laravel Excel and doing an export by returning a view. I wrote a phpunit test and tried using assertViewHas and it failed as well with the same error in the original post. After reading this, I did a dd on the response and saw while I'm using `view()` it's a different kind of one so the unit tests helpers don't work.

**Comment by gianngnk** [comment]
- Laravel 5.8.33
- PHPUnit 7.5.15
- PHP 7.1.31

Hello guys, 

I don't know if someone found a solution . I have faced the same problem and i have not found any solution yet. However, after a long time investigation i can confirm that the problem is with the HTML <body> element inside a blade.  If you remove the <body> element from the blade you are testing (that's why @joseraul when you removed @include directive the issue disappeared - i suppose your include file or a layout contained a <body> element ) the assertViewIs will work properly.  It seems that the <body> triggers the render() view method and the response ($response->original) returns the view as a string instead as a View object. If you will look deeper during the test you will see that the `"blade.compiler" => Illuminate\View\Compilers\BladeCompiler {` has the #path equals to null instead of the path of the related view (blade) of the test.

Do you have any ideas?

**Comment by R1Daneel** [comment]
@gianngnk I had the same problem; the `$response->original` is a simple string.

**Comment by jj-meyer** [comment]
For anyone that finds this issue/discussion via google, it assisted to resolve my issue as follows: It appears that both `barryvdh/laravel-debugbar` and `beyondcode/laravel-query-detector` influence the way that a view is returned, if enabled. 

I resolved my issue by disabling either or both these packages during testing by adding

```
        <server name="DEBUGBAR_ENABLED" value="false"/>
        <server name="QUERY_DETECTOR_ENABLED" value="false"/>
```
to the `php` section of `phpunit.xml`
