### ISSUE TITLE
[5.6] Cyclic serialization of relationships

### ISSUE THREAD

**Issue by abler98** [laravel/framework#23505]
- Laravel Version: 5.6.11
- PHP Version: 7.1
- Database Driver & Version: MySQL 5.7

### Description:

A new SerializesModels helper causes cyclic serialization of relations.

### Steps To Reproduce:

There is the following code:
```php
$trip = new Trip();
$trip->request()->associate($request);
$trip->save();

$request->trip()->associate($trip);
$request->save();

// This causes cyclic serialization of relations
serialize(new TripAccepted($trip));
```
TripAccepted class:
```php
class TripAccepted
{
    use SerializesModels;
    
    public $trip;

    ...
}
```

Since the trip has a request relation, and request has a trip relation, serialization recursively getting a list of loaded relations:
https://github.com/laravel/framework/blob/5.6/src/Illuminate/Database/Eloquent/Model.php#L1302

Translated using Google Translate.

**Comment by cvc1989** [comment]
Running into a potentially related issue with this same area of code.  Getting the recursive calls (running out of memory) when passing an eloquent model in an event which has multiple listeners subscribed.

Reversing these changes appears to fix the issue for me locally: https://github.com/laravel/framework/pull/23081/files

**Comment by fredjiles** [comment]
We are running into this same issue.  I will see if I can create a failing test for this tomorrow.  We are seeing the exact same issue where we have a BelongsTo and HasMany and the relationship is set on both sides.  When the BelongsTo is serialized it goes into an infinite loop.

**Comment by xakzona** [comment]
Same issue. Error: Maximum function nesting level of '256' reached, aborting!

**Comment by xakzona** [comment]
I have found temporary resolution: 
```
public function __construct(Photo $photo)
    {
        parent::__construct();
        $photo->setRelations([]);
        $this->photo = $photo;
    }
```

**Comment by driesvints** [comment]
@abler98 can you please post more code to reproduce this problem? any models and their relationships, the job etc.

**Comment by driesvints** [comment]
Does the problem also occur on 5.7?

**Comment by xakzona** [comment]
Example code
`
class phone{
 public function client()
{
return hasOne(Client::class)
}
}

class client{
 public function phone()
{
return hasOne(Phone::class)
}
}

dispatch(new Job($client))
`

**Comment by driesvints** [comment]
@xakzona you're defining the wrong relation in one of the models. The reverse should be `belongsTo`.

https://laravel.com/docs/5.7/eloquent-relationships#one-to-one

**Comment by xakzona** [comment]
Yeap, mistake in example, it was fixed

**Comment by driesvints** [comment]
If anyone can confirm that this also happens in 5.7 I'll happily re-open this.

**Comment by c-zenker** [comment]
I found this (or something similar) still being an issue for me in 5.8.21.
The serialize keeps stuck calling the getQueueableRelations() method of the Eloquent Model and Collections.

Example:

Relation:
Order 1<---->* Line

In Oder Model:
```php
public function lines() {
    return $this->hasMany(OrderLine::class, 'orderId');
}
```

In Line Model:
```php
public function order() {
    return $this->belongsTo(Order::class, 'orderId');
}
```

Job/Mail:
```php
class MyMail extends Mailable implements ShouldQueue {
    use InteractsWithQueue, SerializesModels;

    private $order;
    public function __construct(Order $order) {
        $this->order = $order;
    }
   //...
}
```

Stack trace:
```
... stuck here
#9925 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(556): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9926 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1422): Illuminate\\Database\\Eloquent\\Collection->getQueueableRelations()
#9927 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1428): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9928 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(556): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9929 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1422): Illuminate\\Database\\Eloquent\\Collection->getQueueableRelations()
#9930 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1428): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9931 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(556): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9932 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1422): Illuminate\\Database\\Eloquent\\Collection->getQueueableRelations()
#9933 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1428): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9934 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Collection.php(556): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9935 /var/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1422): Illuminate\\Database\\Eloquent\\Collection->getQueueableRelations()
#9936 /var/www/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(33): Illuminate\\Database\\Eloquent\\Model->getQueueableRelations()
#9937 /var/www/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(23): App\\Mail\\MyMail->getSerializedPropertyValue(Object(App\\Models\\Order))
#9938 [internal function]: App\\Mail\\MyMail->__sleep()
#9939 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(139): serialize(Object(Illuminate\\Mail\\SendQueuedMailable))
#9940 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(110): Illuminate\\Queue\\Queue->createObjectPayload(Object(Illuminate\\Mail\\SendQueuedMailable), 'mail')
#9941 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(88): Illuminate\\Queue\\Queue->createPayloadArray(Object(Illuminate\\Mail\\SendQueuedMailable), 'mail', '')
#9942 /var/www/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(82): Illuminate\\Queue\\Queue->createPayload(Object(Illuminate\\Mail\\SendQueuedMailable), 'mail', '')
#9943 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(44): Illuminate\\Queue\\DatabaseQueue->push(Object(Illuminate\\Mail\\SendQueuedMailable), '', 'mail')
#9944 /var/www/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(180): Illuminate\\Queue\\Queue->pushOn('mail', Object(Illuminate\\Mail\\SendQueuedMailable))
#9945 /var/www/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(388): Illuminate\\Mail\\Mailable->queue(Object(Illuminate\\Queue\\QueueManager))
#9946 /var/www/vendor/laravel/framework/src/Illuminate/Mail/PendingMail.php(155): Illuminate\\Mail\\Mailer->queue(Object(App\\Mail\\Order\\Order))
#9947 /var/www/app/Listeners/Notifier.php(141): Illuminate\\Mail\\PendingMail->queue(Object(App\\Mail\\Order\\Order))
...
```

A workaround was overwriting the getSerializedPropertyValue() Method of the \Illuminate\Queue\SerializesAndRestoresModelIdentifiers trait so that getQueueableRelations() was never called. But still... it's only a workaround


In Job class:
```php
protected function getSerializedPropertyValue($value)
	{
		if ($value instanceof QueueableCollection) {
			return new ModelIdentifier(
				$value->getQueueableClass(),
				$value->getQueueableIds(),
				[], // original: $value->getQueueableRelations(),
				$value->getQueueableConnection()
			);
		}

		if ($value instanceof QueueableEntity) {
			return new ModelIdentifier(
				get_class($value),
				$value->getQueueableId(),
				[], // original: $value->getQueueableRelations(),
				$value->getQueueableConnection()
			);
		}

		return $value;
	}
```

**Comment by hackel** [comment]
@driesvints Still seeing this issue on Laravel 7.14.1.  Here is a minimal testcase:

```php
<?php

use Illuminate\Database\Eloquent\Model;
use Illuminate\Queue\SerializesModels;

class A extends Model {
    public function b()
    {
        return $this->belongsTo(B::class);
    }
}

class B extends Model
{
    public function a()
    {
        return $this->belongsTo(A::class);
    }
}

$a = new A;
$b = new B;
$a->setRelation('b', $b);
$b->setRelation('a', $a);

$serialized = serialize(new class ($a) {
    use SerializesModels;

    public A $a;

    public function __construct(A $a)
    {
        $this->a = $a;
    }
});
```
Running this in tinker gives:
```
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 1514
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65536 bytes) in vendor/nunomaduro/collision/src/ConsoleColor.php on line 202
```

**Comment by kelvinj** [comment]
We've been upgrading an old Laravel app to Laravel 8.

When using a queue (not sync), we started seeing occassional segmentation faults.

A good few hours later, and I narrow it down to the `getQueueableRelations()` method as introduced in #21229.

Also referenced in #26877.

The problem comes from the attempt to automatically traverse nested relationships as if they're a tree. We have fixed this issue by overriding this method in our Models with the following:

```php
    public function getQueueableRelations()
    {
        /**
         * This introduced seg faults during serialize function call
         * where 1 of the relations had a relationship defined back to
         * the initial model, thus creating an infinite loop.
         *
         * @see Model::getQueueableRelations()
         * @see https://github.com/laravel/framework/issues/23505
         */
        $relations = [];

        foreach ($this->getRelations() as $key => $relation) {
            if (!method_exists($this, $key)) {
                continue;
            }

            $relations[] = $key;
        }

        return array_unique($relations);
    }
```
