### ISSUE TITLE
When ValidationException is thrown, user is redirected to /

### ISSUE THREAD

**Issue by KubqoA** [laravel/framework#26945]
- Laravel Version: 5.7.19
- PHP Version: 7.2.13
- Database Driver & Version: PostgreSQL 11.1

### Description:
When `LoginController` (`Illuminate\Foundation\Auth\AuthenticatesUsers`) throws new `ValidationException` user is redirected to `/`. I tried to debug the issue myself and found out that the `ValidationExcpetion` the controller throws has attribute `redirectTo` set to `null`. If I change this attribute to `/login` it redirects successfully. I don't know the inner workings of Laravel that well, so this may not be the thing that causes the issue. However any help will be appreciated.

### Steps To Reproduce:
1. Create a new Laravel app an set up your environment
2. Do `php artisan make:auth`
3. Go to `/login` and input some invalid data
4. It should redirect you to `/`

**Comment by aaronkorn** [comment]
can you give me an example of an invalid data? All I got is 'These credentials do not match our records.'

**Comment by devcircus** [comment]
Following the provided steps, I'm redirected back to the login page with the message "credentials don't match".

**Comment by KubqoA** [comment]
Okay, I just did `laravel new test`, set up testing PostgreSQL database, did `artisan make:auth` and `serve`. I opened the browser to login page, entered some dummy data, and it redirected me to homepage.
In `Illuminate\Foundation\Auth\AuthenticatesUsers` in `login()` it fails at line 53, where it returns the failed login response. The function `sendFailedLoginResponse()` calls `ValidationException::withMessages()`, this creates the following `ValidationException` instance.
````
ValidationException {#246 ▼
  +validator: Validator {#242 ▶}
  +response: null
  +status: 422
  +errorBag: "default"
  +redirectTo: null
  #message: "The given data was invalid."
  #code: 0
  #file: "/tmp/test/vendor/laravel/framework/src/Illuminate/Validation/ValidationException.php"
  #line: 71
  trace: {▶}
}
````
However as you can see the attribute `redirectTo` is `null`. I suspect this might be the issue, but I am not sure. This instance then gets thrown and the user is redirect to the homepage (`localhost:8000/`).
I installed Laravel Telescope to see what's going on. [This is the screenshot](https://screenshots.firefox.com/jOlT4O4nFI16Ecpt/localhost) of the `/login` POST request.

I also installed `laravel-debugbar`. Which upon me being redirect to homepage tells me that the `/login` POST reuqest (shown as stacked) gave one exception.
````
The given data was invalid./tmp/test/vendor/laravel/framework/src/Illuminate/Validation/ValidationException.php#71
    */
    public static function withMessages(array $messages)
    {
        return new static(tap(ValidatorFacade::make([], []), function ($validator) use ($messages) {
            foreach ($messages as $key => $value) {
                foreach (Arr::wrap($value) as $message) {
                    $validator->errors()->add($key, $message);
````

This is all the data I managed to obtain by debugging. Hopefully this is helpful. Also here is an [output of `php -i`](https://privatebin.net/?36e733f370064da8#x4Lo6P/AhEVwbfBLzC3oT1Bi+iCoWahqamUbSFQtHwc=), maybe it can also prove to be helpful

**Comment by xuanquynh** [comment]
I don't really understand what you really want. I confused about step 4 of "Steps To Reproduce":
- What is your expected results?
- What is your actual results?

Anyway, the ValidationException is handled by Illuminate\Foundation\Exceptions\Handler:

```php
/**
 * Convert a validation exception into a response.
 *
 * @param  \Illuminate\Http\Request  $request
 * @param  \Illuminate\Validation\ValidationException  $exception
 * @return \Illuminate\Http\Response
 */
protected function invalid($request, ValidationException $exception)
{
    return redirect($exception->redirectTo ?? url()->previous())
                ->withInput($request->except($this->dontFlash))
                ->withErrors($exception->errors(), $exception->errorBag);
}
```

**Comment by KubqoA** [comment]
Maybe the issue on this line in the `Handler`:
````
return redirect($exception->redirectTo ?? url()->previous())
````
I used `dd(url()->previous())` to see what does Laravel think my previous route is and it turns out, the output is my root url: `"http://project.test/"`.

Has anybody ever encountered this?

**Comment by devcircus** [comment]
Sounds like sessions may not be working correctly. If you login successfully, then refresh the page, do you stay logged in?

**Comment by KubqoA** [comment]
Yes, I stay logged in.

**Comment by devcircus** [comment]
Can you push a project to github that has this issue, so we can check it out?

**Comment by KubqoA** [comment]
Well as I mentioned earlier, the problem seems to be rather odd, as I experience this issue across all my Laravel projects. Thus, I think the problem is not in the Laravel framework itself. Possibly it is something to do with my PHP configuration, or I don't know what else could be causing this.

**Comment by xuanquynh** [comment]
I have no idea. I haven't ever got the same issue before. This feature works normally for me.

**Comment by xuanquynh** [comment]
You should make `Steps To Reproduce` section such as:

```
1. Create a new Laravel app an set up your environment
2. Do php artisan make:auth
3. Go to /login and input some invalid data

## Expected
- The application redirects the user back to login with errors.

## Actual
- The application redirects the user to the home page. (that means the user has been loged in successfully).
```

May any others help you?

**Comment by KubqoA** [comment]
No as the user is redirected to the home page without being logged in successfuly

**Comment by xuanquynh** [comment]
Well, I don't think this issue is raised by the core Framework. All my Laravel projects work normally. I have no idea.

**Comment by ahinkle** [comment]
Unable to replicate using same PHP version.  Displays the proper validation message within `/login`. It seems as if you have a bunch of extra packages that aren't mentioned in your original post that may cause some redirects. (nova, etc)

**Comment by KubqoA** [comment]
Okay I did:
1. `laravel new project`
2. I set up the database (PostgreSQL 11) and ran migration files
3. I did `php artisan make:auth`
4. I ran `php artisan serve`
5. Opened `localhost:8000` and went to `/login`
6. I inputed `test@example.com` and `password` to the login page (invalid data)
7. I got redirected back to `localhost:8000/` e.g. the root

**Comment by KubqoA** [comment]
I also tried uninstalling my PHP, removing all the config files, installing a fresh copy of the newest PHP (7.3.0), but still it doesn't work for some unknown. reason.

**Comment by driesvints** [comment]
I realize a lot of people have already tried helping you here but can you please try one of the below support channels instead? This issue tracker isn't meant to be used to get support with an application related problem. I also highly doubt this is an issue with the framework itself.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)
- [StackOverflow](https://stackoverflow.com)

**Comment by KubqoA** [comment]
Okay, I am sorry I bothered everyone with this issue. Just now, I got an idea, whether it could be caused by the browser. So I opened the site in another browser and it worked. Probably some add-on is misbehaving or my tinkering with Firefox's `about:config` has broke something. Anyways, thanks for the help.

**Comment by and-koghb** [comment]
I met the same issue with Laravel 7.
When I add this function to my LoginController
`protected function attemptLogin(Request $request)
    {
        $attempt = $this->guard()->attempt(
            $this->credentials($request), $request->filled('remember')
        );
        if (!$attempt) {
            return false;
        }

        $user = $this->guard()->getLastAttempted();
        if ($user->status != Common::STATUS_ACTIVE) {
            throw ValidationException::withMessages([
                $this->username() => __('Your account is inactive.'),
            ]);
        }
        return true;
    }`
    it logs in the user anyway, `throw ValidationException` isn't working.
    
    But if I add this function (without adding the previous one)
    `protected function validateLogin(Request $request)
    {
        $user = User::where('email', $request->email)->first();
        if ($user && $user->status != Common::STATUS_ACTIVE) {
            throw ValidationException::withMessages([$this->username() => __('Your account is inactive.')]);
        }

        return $request->validate([
            $this->username() => 'required|string',
            'password' => 'required|string',
        ]);
    }`
    it works normally, redirects to login page, and I see validation error message.

**Comment by ahinkle** [comment]
@and-koghb Laravel 7 isn't supported and is EOL; upgrade to Laravel 8 to see if that solves your issue.

**Comment by and-koghb** [comment]
@ahinkle , my issue is solved, I wrote the solution in my comment: "o make the first function working properly, we just need to add $this->guard()->logout(); before ValidationException".
Thank you.

**Comment by sebsobseb** [comment]
This might help others who have this issue. 

I had the same issue in Laravel 8: When on `/login` and entering wrong login credentials it redirected to the `/` instead of back to `/login`. I can confirm this "bug" is not present in a fresh Laravel 8 project.

But, I found that the underlying problem was that `url()->previous()` always returned the root url.
Behind the scene `url()->previous()` will read from the **referrer** header, **and that's where my problem was.**

This HTML meta tag was present in my blade and caused the referrer header to always be the root url:
`<meta name="referrer" content="strict-origin" />`

**Removing** this HTML meta tag solved the problem! **Or replace** with:
`<meta name="referrer" content="origin-when-cross-origin" />`

**Comment by nateritter** [comment]
@sebsobseb Thank you so much!  This helped me immensely!  It's been months that I've been hearing of this bug and I couldn't track it down. Thank you a thousand times over (and from my users too)!

**Comment by Dogunfx** [comment]
i 

> This might help others who have this issue.
> 
> I had the same issue in Laravel 8: When on `/login` and entering wrong login credentials it redirected to the `/` instead of back to `/login`. I can confirm this "bug" is not present in a fresh Laravel 8 project.
> 
> But, I found that the underlying problem was that `url()->previous()` always returned the root url. Behind the scene `url()->previous()` will read from the **referrer** header, **and that's where my problem was.**
> 
> This HTML meta tag was present in my blade and caused the referrer header to always be the root url: `<meta name="referrer" content="strict-origin" />`
> 
> **Removing** this HTML meta tag solved the problem! **Or replace** with: `<meta name="referrer" content="origin-when-cross-origin" />`

Hello,

 i am not having the tag <meta name="referrer" content="strict-origin" />
 
 on my blade file but i am still getting the same issues,
