### ISSUE TITLE
Won't display literal '@parent'

### ISSUE THREAD

**Issue by rettigd** [laravel/framework#28693]
- Laravel Version: 5.1 and 5.8 (probably everything in between)
- PHP Version: 7.1
- Database Driver & Version:

### Description:
Any text with the literal '@parent' is removed from the html during render when it's in a child blade template. In 5.1 @parent gets removed no matter the context (email@parentsomething.com renders as emailsomething.com), but in 5.8 @parent gets removed if the string is exactly '@parent', but email@parentsomething.com renders properly. I'm running 5.1. 

### Steps To Reproduce:
create new app
update welcome page with @yield('content') in the content div
create new blade template with 
```@extends('welcome')```
```@section('content')```
 ```   {{ '@parent' }}```
```@endsection```
update routes to load new template

For grins (5.8) try 
```{{ substr('@parent',0,10) }}```

**Comment by laurencei** [comment]
This has been an issue since Laravel 5.0.

Here's where I mentioned it in 2015: https://github.com/laravel/framework/issues/7888

@themsaid did a fix for it in most situations here: https://github.com/laravel/framework/pull/16033

It's a complicated issue, and I would suggest this is a limitation of blade.

From memory - try doing `@@parent` - does that show `@parent` as expected?

**Comment by rettigd** [comment]
Changing content to @@parent doesn't seem to be a reasonable solution. I have customers with domains that have @parent in them. These users think that their email addresses are incorrect since the @parent portion is removed from the render. Seems odd that we can't display this string on a Laravel site.

**Comment by laurencei** [comment]
> I have customers with domains that have @parent in them

But this is fixed in the 5.8 Laravel? 5.1 isnt supported, and no fix would be backported there.

Seems the answer would be to upgrade, or manually apply the fix that themsaid did to your install?

**Comment by rettigd** [comment]
I really didn't expect 5.1 to be fixed, but it should have if this was known in 5.0. Disappointing that this wasn't back-ported 2 years ago considering it's treating content as code.
 
And it's only partially fixed in 5.8  since ```{{ '@extends' }}``` causes an exception in 5.8 - or maybe this should be a different issue.

**Comment by driesvints** [comment]
In Laravel 5.8 when I put the following in a blade file (with `$parent` being `'@parent'`:

```blade
@parent
<br><br>
@@parent
<br><br>
hi@parent
<br><br>
hi@parent.com
<br><br>
{{ 'hi@parent' }}
<br><br>
{{ 'hi@parent.com' }}
<br><br>
@{{ '@parent' }}
<br><br>
{{ '@parent' }}
<br><br>
@{{ 'parent' }}
<br><br>
{{ $parent }}
```

It renders to:

```
##parent-placeholder-da39a3ee5e6b4b0d3255bfef95601890afd80709## 

@parent 

hi@parent 

hi@parent.com 

hi@parent 

hi@parent.com 

{{ '##parent-placeholder-da39a3ee5e6b4b0d3255bfef95601890afd80709##' }} 

##parent-placeholder-da39a3ee5e6b4b0d3255bfef95601890afd80709## 

{{ 'parent' }} 

@parent
```

So email addresses should be fine. Everything for above renders as expected for me. Strings passed with '@' signs in them will render properly. If you directly place strings with `@parent` or `@extends` in blade views you have to take into account that they're blade directives and need to be properly handled. You can escape them like @laurencei suggested.
