### ISSUE TITLE
Date milliseconds turn into zeros on model saving

### ISSUE THREAD

**Issue by andriihorpenko** [laravel/framework#31058]
- Laravel Version: 6.9.0
- PHP Version: 7.4.0
- Database Driver & Version: MySQL 5.7.28

### Description:
Whenever I try to save a model with Carbon instance having a date with milliseconds Laravel "replaces" milliseconds with zeros and hence loses date precision. Further details in the next sections.

### Steps To Reproduce:
1. Create a new/parse existing date with milliseconds precision using Carbon. For this case I am using Carbon::createFromTimestampMs($timestamp)
2. Assign Carbon's instance to model's timestamp field that is listed in model's $dates field and has $dateFormat set to 'Y-m-d H:i:s.u'
3. Save the model and view the results

### Example (using preudo code)
Model's timestamp field: sent_at (precision set to 6 in migration file)
$timestamp: 1578428730370
Result of Carbon::createFromTimestampMs($timestamp):
![image](https://user-images.githubusercontent.com/13716167/71929640-c18e1a80-31a2-11ea-8562-0b709cdefb7b.png)
Result of $model->sent_at after saving a model:
![image](https://user-images.githubusercontent.com/13716167/71929807-192c8600-31a3-11ea-8c7a-0d8674da19e9.png)

**Comment by laurencei** [comment]
This SO question and answer implies it might be a limitation of the PHP PDO driver?

https://stackoverflow.com/q/31227069/1317935

But that answer is a few years old - so I'm not sure.

**Comment by andriihorpenko** [comment]
As far as I remember this bug was fixed on the PDO driver side years ago, correct me if I am wrong.

**Comment by driesvints** [comment]
Hmm, this might be the same one as https://github.com/laravel/framework/issues/31049

@kylekatarnls do you have any idea what's going on here?

**Comment by kylekatarnls** [comment]
Does the SQL field has enough precision (e.g. `->timestamp('sent_at', 6)` vs `->timestamp('sent_at')`) in the migration file?

**Comment by andriihorpenko** [comment]
Yes, I do have a precision set in the migration file.

**Comment by kylekatarnls** [comment]
Can you double-check by checking the SQL schema of the table (with phpMyAdmin for instance) to see if the migration ran well.

**Comment by antonkomarev** [comment]
There was a bug in PHP https://bugs.php.net/bug.php?id=67122 but it was fixed https://github.com/php/php-src/commit/71c04324b7161f9ed151e9550a1a6764c5d170f7

**Comment by kylekatarnls** [comment]
Yep, this can't happen with PHP 7.4.0.

**Comment by andriihorpenko** [comment]
It's getting weirder. I've just restarted the server and rerun model creation. Now it is saving everything properly and I have expected result:
![image](https://user-images.githubusercontent.com/13716167/72093243-ae06bf00-331c-11ea-953c-b02681c19080.png)
Moreover, I did server restarts earlier and issue persisted. I haven't done any changes to the server's config files. Can we consider this a bug or would you rather say it is some sort of "caching"? Maybe I can do any more tests for you to investigate the issue.

**Comment by kylekatarnls** [comment]
You noted a behavior that would not the one you expected, you can legitimately consider it's an error. But it may be an error in your app, your usage or in Laravel code or dependencies. To validate the third hypothesis, we need a reproductible use case.

The fact is using same version as you of Laravel, PHP and MySQL and following the steps does not leads me to getting your output. So I guess we would need more "proofs". 

Irrefutable proof, would be a unit test describing your case that would fail on Travis-CI.

If you don't reproduce it this way, then we need more clues on required conditions to make the failure to happen.

**Comment by andriihorpenko** [comment]
Fair enough. I will collect as much info as I can and create a test case. For now I think this issue should be closed as “not reproducible” and if I will be able to recreate it I will let you know. Thanks for your time.

**Comment by driesvints** [comment]
@kylekatarnls thanks for checking in on this 👍
