### ISSUE TITLE
Response sequences make real requests when the sequence is empty, and they are set to not fail

### ISSUE THREAD

**Issue by SjorsO** [laravel/framework#31565]
- Laravel Version: 7.0
- PHP Version: not relevant
- Database Driver & Version: none

### Description:

Related issue: https://github.com/laravel/framework/issues/31519

The new HTTP client makes real requests when a sequence is out of responses, and is set to not fail when empty:
 
### Steps To Reproduce:
```php
$factory = new Factory;

$factory->fakeSequence()
    ->dontFailWhenEmpty()
    ->push('Ok');

$this->assertSame('Ok', $factory->get('https://laravel.com')->body());

// This assertion fails because a real request was made 
$this->assertSame('', $factory->get('https://laravel.com')->body());
```

**Comment by driesvints** [comment]
Please fill out the issue template when reporting bugs.

**Comment by taylorotwell** [comment]
What behavior are you expecting. If you think the behavior should be different then feel free to PR an alternative. Personally I think the current behavior is about what I would expect to happen given the methods called.

**Comment by driesvints** [comment]
@SjorsO I was a bit confused myself at first but what Taylor says makes perfect sense. You're instantiating an *actual* factory instance. It's best to only use it as described in the docs: https://laravel.com/docs/master/http-client#testing

**Comment by SjorsO** [comment]
> What behavior are you expecting. If you think the behavior should be different then feel free to PR an alternative. Personally I think the current behavior is about what I would expect to happen given the methods called.

I would expect that no real requests are made when `Http::fake()` is used, the same way no mails are sent when using `Mail::fake()`, and no jobs are executed when using `Queue::fake()`. 

Accidentally doing create/update/delete http calls when running unit tests shouldn't be something you have to worry about when using `Http::fake()`

> @SjorsO I was a bit confused myself at first but what Taylor says makes perfect sense. You're instantiating an _actual_ factory instance. It's best to only use it as described in the docs: https://laravel.com/docs/master/http-client#testing

The `fake()` method is on the real factory, I don't think there is any difference calling it from the facade or directly on a factory.

**Comment by driesvints** [comment]
@SjorsO can you confirm that and add some code snippets for us to test?

**Comment by SjorsO** [comment]
> @SjorsO can you confirm that and add some code snippets for us to test?

Route:
```php
Route::get('/', function () {
    $response = Http::get('https://laravel.com');

    return $response->body();
});
```

Test:
```php
public function testBasicTest()
{
    Http::fakeSequence()->dontFailWhenEmpty();

    $this->get('/')
        ->assertDontSee('Laravel');
}
```

This test fails because a real request is made, and the real response is returned.

If this is expected behavior, I would suggest removing the `dontFailWhenEmpty()` method.

**Comment by driesvints** [comment]
@SjorsO `fakeSequence` isn't documented at all. This works for me:

```php
    /**
     * A basic test example.
     *
     * @return void
     */
    public function testBasicTest()
    {
        \Http::fake();

        $this->get('/')
            ->assertDontSee('Laravel');
    }
```

**Comment by SjorsO** [comment]
> @SjorsO `fakeSequence` isn't documented at all. This works for me:
> 
> ```
>     /**
>      * A basic test example.
>      *
>      * @return void
>      */
>     public function testBasicTest()
>     {
>         \Http::fake();
> 
>         $this->get('/')
>             ->assertDontSee('Laravel');
>     }
> ```

`fakeSequence` is syntactic sugar, it will also behave like this when using the "documented" way of doing it

`fakeSequence` was added in this pr https://github.com/laravel/framework/pull/31535

**Comment by taylorotwell** [comment]
Fixed.

**Comment by SjorsO** [comment]
When I created [the PR](https://github.com/laravel/framework/pull/31532) that makes response sequences fail when they run out of responses, issue https://github.com/laravel/framework/issues/31519 was not fixed yet, so every fake call was doing real responses. I assumed that this bug also affected the response sequences, and that they should have been returning 200 responses by default (like mentioned in the original PR).

The fix you implemented is what I was assuming should be happening in this situation. Iit might be an idea to remove the `->dontFailWhenEmpty()` method entirely. I can't think of a scenario where you would want to use it. The only reason I added it to my PR was to provide a way to keep the old behavior, which usually improves the chances of a PR getting merged.

**Comment by davorminchorov** [comment]
@taylorotwell @driesvints I have a similar issue, wrote more about it here: https://laracasts.com/discuss/channels/testing/httpfake-is-ignored-and-the-real-http-request-is-being-fired-to-an-external-api

If I use the Http facade in my code, it works fine and the fake response is returned, but if I use the actual Factory class with dependency injection, it will keep hitting the real API in the test. 

That makes the Http client inconsistent, compared to other classes like Mail, Notification, Queue, and Storage, like @SjorsO mentioned, where you could do Class::fake() and use dependency injection in the code and it works fine.

**Comment by danielsdeboer** [comment]
@davorminchorov Not 100% sure why resolving the `Factory` out of the container is any different than using the `Http` facade, but I've been able to work around it by using contextual binding in my tests:

```php
$this->app->when(MyClass::class)
    ->needs(Factory::class)
    ->give(fn () => (new Factory())->fake([
        // fake stuff
    ]));
```
