### ISSUE TITLE
Eloquent pagination and distinct

### ISSUE THREAD

**Issue by adobi** [laravel/framework#35597]
- Laravel Version: 8.2.1
- PHP Version: 7.4.2
- Database Driver & Version: MySql 5.7.26

### Description:
Eloquent pagination calculates the total number of pages wrong when we have a distinct in the columns list.

### Steps To Reproduce:
1. Create a query where you have multiple joins and a distinct in the columns list. Something like this

``` 
$builder = $this->model->query()
            ->select('users.*')
            ->join('roles', 'users.role_id', '=', 'roles.id')
            ->leftJoin('companies', 'users.company_id', '=', 'companies.id')
            ->leftJoin('groups', 'users.group_id', '=', 'groups.id')
            ->leftJoin('company_group', 'company_group.group_id', '=', 'groups.id')
            ->leftJoin('companies as c2', 'company_group.company_id', '=', 'c2.id')
            ->distinct()
        ;
```

2. Call the `$builder->paginate(10, 'users.id')`
3. This will return every row without the distinct.

### Possible solution
Maybe if we pass the `$columns` in the `illuminate/database/Eloquent/Builder.php:732` to the `getCountForPagination` function to use it?

**Comment by driesvints** [comment]
Please see #26935 and numerous other issues.

**Comment by driesvints** [comment]
Well actually, this should have been resolved since https://github.com/laravel/framework/pull/27675 was merged. But I'm guessing there's something wrong with your query.

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to report back and I'll gladly help you out and re-open this issue.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by adobi** [comment]
Hi @driesvints ,

Thank for the quick reply. I ran the sql of query in the mysql console and gave me the right solution. So I assume the query is working. I will keep searching for an answer for my problem because I still don't see what am I doing wrong. I still think this is a bug :/

**Comment by RoobieBoobieee** [comment]
@adobi 
Instead of passing the distinct column `users.id` in the paginate method. Pass it to the distinct method as an array. 
```
...
->distinct(['users.id']);
```

**Comment by shapesdefined** [comment]
> @adobi Instead of passing the distinct column `users.id` in the paginate method. Pass it to the distinct method as an array.
> 
> ```
> ...
> ->distinct(['users.id']);
> ```

This solution is working. Thanks

**Comment by tauseedzaman** [comment]
got the same issue but solved by using groupby("field name")->paginate()..
