### ISSUE TITLE
Renaming timestamp columns converts them to datetime

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [laravel/framework#39959]
- Laravel Version: 8.75.0
- PHP Version: 7.4.26
- Database Driver & Version: 8.0.26

### Description:

Renaming a timestamp column ends up converting it to a datetime.

### Steps To Reproduce:

```PHP
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSubscriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('subscriptions', function (Blueprint $table) {
            $table->id();
            $table->timestamp('membership_starts_at')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('subscriptions');
    }
}
```

```PHP
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class ChangeSubscriptionsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('subscriptions', function (Blueprint $table) {
              $table->renameColumn('membership_starts_at', 'billing_starts_at');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
            $table->renameColumn('billing_starts_at', 'membership_starts_at');
    }
}
```

Now check the table schema and you will see that `billing_starts_at` is a `datetime` not a `timestamp`.

**Comment by driesvints** [comment]
Hi there,

Thanks for reporting but it looks like this is a question which can be asked on a support channel. Please only use this issue tracker for reporting bugs with the library itself. If you have a question on how to use functionality provided by this repo you can try one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by ChrisThompsonTLDR** [comment]
This isn't a question.  It's a bug. `renameColumn()` changes the column type.

**Comment by thelfensdrfer** [comment]
I fail to see the question.

**Comment by dpatonMYCM** [comment]
I don't see a question here either. It is a genuine bug report I just tested and got the same result.

I really do appreciate all the work the core Laravel team does but since this repo hit 0 issues it seems as though there some bias leaning towards closing issues as quickly as possible and sometimes genuine issues being marked as questions.

**Comment by fieryprophet** [comment]
> Please only use this issue tracker for reporting bugs with the library itself.

![image](https://user-images.githubusercontent.com/533700/145428603-175f4816-2814-464c-8caa-3a40b62aee75.png)

**Comment by ceejayoz** [comment]
@driesvints This appears to be a legitimate "bug with the library itself". Please re-open; `renameColumn` should not under any circumstances silently change the column's data type.

**Comment by driesvints** [comment]
We don't handle that part. We use DBAL under the hood to do column rewrites. I've seen this pop up before and remember this wasn't a bug but expected behaviour. Please either search the issue tracker or report it to the DBAL issue tracker if you really think this is a bug.

**Comment by ceejayoz** [comment]
OK, so the feedback is less "this is a question which can be asked on a support channel" and more "report it upstream to DBAL"?

**Comment by driesvints** [comment]
Btw, to everyone downvoting me here: instead of immediately assuming I didn't mean well, assume I do this for a reason. I see countless issues every day that could have been solved by simple asking on support channels beforehand instead of immediately opening an issue. We want to help everyone as well as possible but if everyone would post their first thought immediately on this issue tracker we couldn't keep up anymore.

Here's exactly the reasoning for this behaviour after one simple search on the issue tracker: https://github.com/laravel/framework/issues/35498

@ceejayoz depends if you see this as unexpected behaviour. If you do, then yes.

**Comment by dpatonMYCM** [comment]
@driesvints Since this is a DBAL issue could this be added to the docs stating that renaming timestamp fields will currently cause them to change to datetime fields. Similar to how it currently states that renaming enum fields is not supported

**Comment by driesvints** [comment]
@dpatonMYCM we're open to PR's

**Comment by thelfensdrfer** [comment]
> Here's exactly the reasoning for this behaviour after one simple search on the issue tracker: #35498

The issue and pr #35591 are about implementing a new config option, so that the timestamp column IS available in laravel. I couldn't find mentions for the behavior explained by @ChrisThompsonTLDR, but maybe I am overlooking something.

**Comment by ajoy39** [comment]
> Btw, to everyone downvoting me here: instead of immediately assuming I didn't mean well, assume I do this for a reason. I see countless issues every day that could have been solved by simple asking on support channels beforehand instead of immediately opening an issue. We want to help everyone as well as possible but if everyone would post their first thought immediately on this issue tracker we couldn't keep up anymore.
> 
> Here's exactly the reasoning for this behaviour after one simple search on the issue tracker: #35498
> 
> @ceejayoz depends if you see this as unexpected behaviour. If you do, then yes.

You linked to where timestamp was added as an option but it still doesn't explain why changing the column would cause the column data type to change when the Laravel framework supports it. I understand you get lots of open issues that are support requests, not bug reports, but I fail to see how a Laravel method changing the datatype of a column when it shouldn't is not a laravel bug regardless of the fact that the core of the issue is that DBAL doesn't natively support timestamps. To say that this is not a bug is to say that we, as developers, cannot trust any bit of laravel code that relies on an outside library because Laravel will just say "well no the rename column shouldn't change the data type of the column, but it does because DBAL does". This part of the app relies on DBAL but it is wrapped in Laravel syntax, it's a laravel method I'm calling to rename the column, not a DBAL one, and that method also changed the data type of my column. It's a bug. A hard one to catch, granted, and one that is fundamentally caused by the underlying library, but still a bug.

**Comment by ChrisThompsonTLDR** [comment]
Going into reporting this, I figured it was a dbal issue, but feel the same way as @ajoy39.  When I find a Laravel method that doesn't work as expected, I report it to Laravel.

**Comment by driesvints** [comment]
Also want to apologise if I handled this poorly initially.

**Comment by dpatonMYCM** [comment]
> Also want to apologise if I handled this poorly initially.

When looking from your perspective I don't think you handled this poorly. You have an awful lot more experience with the niche quirks that occasionally (but very rarely) pop up in Laravel. As has been established this was a somewhat known issue that you with experience knew about so how you initially responded is completely logical when looking at it from that angle. 


Again thankyou for all the work you and the rest of the core team put in

**Comment by ChrisThompsonTLDR** [comment]
@driesvints no worries brother.

**Comment by bakerkretzmar** [comment]
> In the meantime if you want to fix this, you can add the following in a service provider:
> 
> ```
> \Schema::registerCustomDoctrineType(\Illuminate\Database\DBAL\TimestampType::class, 'timestamp', 'timestamp');
> ```

Just to add to this, in my particular case that wasn't enough to get the columns registered properly in tests too. I had to do this in a service provider:

```php
// for each new type $name and its class $class...

if (! Type::hasType($name)) {
    Type::addType($name, $class);
}

DB::connection()
    ->getDoctrineSchemaManager()
    ->getDatabasePlatform()
    ->registerDoctrineTypeMapping($name, $name);
```

It's _almost_ exactly the same, but `Schema::registerCustomDoctrineType()` puts `DB...registerCustomDoctrineTypeMapping()` inside the `if` statement, and in my case that works one time and then isn't recognized in subsequent tests.
