### ISSUE TITLE
Laravel contextual binding does not work with form request

### ISSUE THREAD

**Issue by Temepest74** [laravel/framework#41195]
- Laravel Version: 8.83.2
- PHP Version: 8.1.1

Laravel contextual binding does not work with requests, my example will demonstrate what do I mean.
``` 
class ControllerA extends Controller {
    public function index(RequestA $request) {
    }
}  

class ControllerB extends ControllerA {
    public function index(RequestA $request) {
        dump(get_class($request)); //will print RequestA instead of RequestB, here is the problem.
    }
}  

class RequestA extends FormRequest
{
}

class RequestB extends RequestA
{
}
```
Now, If I use the below code inside RouteServiceProvider, the ControllerB won't have the RequestA bound to it.
```
$this->app->when(ControllerB::class)->need(RequestA)->give(RequestB);
```

**Comment by rodrigopedra** [comment]
Contextual binding works for classes' constructors or resolved from the container using `app()->make(...)` for example.

Controller actions are not resolved from the container.

One option is to resolve it on the controller itself:

~~~php
use App\Http\Requests\BarRequest;
use Illuminate\Http\Request;

public function index(Request $request)
{
    $request = tap(BarRequest::createFrom($request), fn($request) => $request->validateResolved());

    dd($request::class);
}
~~~

Another is to seek help in the support channels:

https://laravel.com/docs/9.x/contributions#support-questions

**Comment by X-Coder264** [comment]
> Controller actions are not resolved from the container.

@rodrigopedra The request and other services that are typehinted on a controller action method ARE resolved from the container using `$container->make();`

https://github.com/laravel/framework/blob/v9.2.0/src/Illuminate/Routing/ControllerDispatcher.php#L40
https://github.com/laravel/framework/blob/v9.2.0/src/Illuminate/Routing/RouteDependencyResolverTrait.php#L80

I don't think contextual binding works for non-constructor dependencies.

In order to accomplish what the issue author wants method binding should be used. Unfortunatelly it's not really documented on the container documentation. The only mention of it is in the queue page (but at least is shows how it's done):

https://laravel.com/docs/9.x/queues#handle-method-dependency-injection

**Comment by rodrigopedra** [comment]
Thanks for the heads up @X-Coder264 , I know that as you can read on this phrase:

> Contextual binding works for **classes' constructors** or resolved from the container using app()->make(...) for example.

Maybe what is confusing on my text is the usage of **"or"** instead of **"and"**. It was late down here and I had phrased it first in a different way and I might have overseen how the phrase ended.

I meant that it wouldn't work for non-constructors methods. But your comment makes it way clearer, thanks :)

**Comment by rodrigopedra** [comment]
One more thing the code snippet I was referring to when I wrote

> Controller actions are not resolved from the container.

https://github.com/laravel/framework/blob/6c0d272a914b43b72056bde1eab9275f6e5093e5/src/Illuminate/Routing/ControllerDispatcher.php#L38-L49

Which as you can see shows that controller actions are not resolved from the container.

Maybe I could have phrased it better.

**Comment by X-Coder264** [comment]
Yeah, the entire sentence `controller actions are not resolved from the container` was confusing, as of course a method cannot be resolved from the container as the container can only resolve objects.

**Comment by rodrigopedra** [comment]
@X-Coder264 this is what I wanted to mean. Thanks!

Sorry English is not my native language. Have a nice day =)

**Comment by driesvints** [comment]
We'd welcome a PR to make that more clearer in the docs. Thanks for helping out @X-Coder264 @rodrigopedra 👍

**Comment by Temepest74** [comment]
@X-Coder264 could you help me with an example based on my code? I have some trouble implementing it

**Comment by Temepest74** [comment]
@driesvints can you reopen this? I tried this code and didn't work.
```
        $this->app->bindMethod([ControllerA::class, 'index'], function (...$params) {
            Log::debug("1");
        });
```
This function will never be called. Please provide me with a working example or at least look into what I am doing wrong.

**Comment by rodrigopedra** [comment]
@Temepest74 you can read the motivation to add this feature on its original PR:

https://github.com/laravel/framework/pull/16800

The idea behind `bindMethods` is to provide all of a method dependencies for a method that will be resolved from the container. All parameters should be provided, as no reflection is done to other parameters.

And also it **only works** for methods that are called from the container, using `app()->call(...)` for example.

Controller actions are **NOT** called from the container. So you won't be able to decorate them using this approach.

Maybe you could extend your controller, and tell the container to resolve your extended class that overrides that method/action based on condition.

Please, further questions should be directed to the support channels, as according to the docs:

> Laravel's GitHub issue trackers are not intended to provide Laravel **help** or **support**. 

reference: https://laravel.com/docs/9.x/contributions#support-questions

See the link above for the support channels links.

**Comment by Temepest74** [comment]
> @Temepest74 you can read the motivation to add this feature on its original PR:
> 
> https://github.com/laravel/framework/pull/16800
> 
> The idea behind `bindMethods` is to provide all of a method dependencies for a method that will be resolved from the container. All parameters should be provided, as no reflection is done to other parameters.
> 
> And also it **only works** for methods that are called from the container, using `app()->call(...)` for example.
> 
> Controller actions are **NOT** called from the container. So you won't be able to decorate them using this approach.
> 
> Maybe you could extend your controller, and tell the container to resolve your extended class that overrides that method/action based on condition.
> 
> Please, further questions should be directed to the support channels, as according to the docs:
> 
> > Laravel's GitHub issue trackers are not intended to provide Laravel **help** or **support**. 
> 
> reference: https://laravel.com/docs/9.x/contributions#support-questions
> 
> See the link above for the support channels links.

So, you just said this is impossible to do? After your colleague approved what the other people said (they said it is possible)

**Comment by rodrigopedra** [comment]
@Temepest74 

First I wrote:

> And also it only works for methods that are called from the container, using app()->call(...) for example.

Here it refers to contextual bindings for methods.

Then I wrote:

> Controller actions are **NOT called from the container**. So you won't be able to decorate them using this approach.

Which is true, and no other answer says the opposite.

What @X-Coder264 wrote is:

> The request and other services that are typehinted on a controller action method ARE resolved from the container using $container->make();

Which means the **dependencies** are resolved from the container, not the method calling. If you look at the code linked in that answer you will see the `ControllerDispatcher` uses reflection to resolve an action's dependencies, it doesn't defer to `$app->call(...)`

And in the PR I linked above it says contextual bindings for methods are only applied to **methods** called from the container. Which a controller's method **is not**.

Resolving dependencies from the container **is different than** calling a method from the container.

Please send further questions to the support channels I linked above per Laravel's policy.

**Comment by Temepest74** [comment]
Oh, ok my bad. I was unable to understand these terms.

**Comment by rodrigopedra** [comment]
No worries, English is not my native language, I might have worded it badly :)
