### ISSUE TITLE
Error starting the server of a new installation of Laravel - ( Carbon:: related)

### ISSUE THREAD

**Issue by Rusbelito** [laravel/framework#53189]
### Laravel Version

11.28.0

### PHP Version

PHP 8.2.4

### Description

I created a new Laravel 11 project, but when I start my local server it crashes.

i first try with "php artisan serve" , when going to the browser with the local url "[http://127.0.0.1:8000]" , It stopped showing this error : 

```
C:\xampp 8_2_4\htdocs\ll11>php artisan serve
  forking is not supported on this platform

   INFO  Server running on [http://127.0.0.1:8000].

  Press Ctrl+C to stop the server


   ErrorException

  Undefined array key 1

  at vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:368
    364▕         $line = str_replace('  ', ' ', $line);
    365▕
    366▕         preg_match($regex, $line, $matches);
    367▕
  ➜ 368▕         return Carbon::createFromFormat('D M d H:i:s Y', $matches[1]);
    369▕     }
    370▕
    371▕     /**
    372▕      * Get the request port from the given PHP server output.

  1   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:368
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1", "C:\xampp 8_2_4\htdocs\ll11\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")

  2   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:297
      Illuminate\Foundation\Console\ServeCommand::getDateFromLine("[Wed Oct 16 10:39:46 2024] 127.0.0.1:50507 Accepted")
```

**Then I thought I should use the boot mode shown in the documentation: "composer run dev" but I got the same result :**

```C:\xampp 8_2_4\htdocs\ll11>composer run dev
> Composer\Config::disableProcessTimeout
> npx concurrently -c "#93c5fd,#c4b5fd,#fb7185,#fdba74" "php artisan serve" "php artisan queue:listen --tries=1" "php artisan pail" "npm run dev" --names=server,queue,logs,vite
[queue]
[queue]    INFO  Processing jobs from the [default] queue.
[queue]
[logs]
[logs]    RuntimeException
[logs]
[logs]   The [pcntl] extension is required to run Pail.
[logs]
[logs]   at vendor\laravel\pail\src\Guards\EnsurePcntlIsAvailable.php:15
[logs]      11▕      */
[logs]      12▕     public static function check(): void
[logs]      13▕     {
[logs]      14▕         if (! function_exists('pcntl_fork')) {
[logs]   ➜  15▕             throw new RuntimeException('The [pcntl] extension is required to run Pail.');
[logs]      16▕         }
[logs]      17▕     }
[logs]      18▕ }
[logs]      19▕
[logs]
[logs]   1   vendor\laravel\pail\src\Console\Commands\PailCommand.php:45
[logs]       Laravel\Pail\Guards\EnsurePcntlIsAvailable::check()
[logs]
[logs]   2   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
[logs]       Laravel\Pail\Console\Commands\PailCommand::handle(Object(Laravel\Pail\ProcessFactory))
[logs]
[logs] php artisan pail exited with code 1
[server]   forking is not supported on this platform
[server]
[server]    INFO  Server running on [http://127.0.0.1:8000].
[server]
[server]   Press Ctrl+C to stop the server
[server]
[vite]
[vite] > dev
[vite] > vite
[vite]
[vite]
[vite]   VITE v5.4.9  ready in 7836 ms
[vite]
[vite]   ➜  Local:   http://localhost:5173/
[vite]   ➜  Network: use --host to expose
[vite]
[vite]   LARAVEL v11.28.0  plugin v1.0.5
[vite]
[vite]   ➜  APP_URL: http://localhost
[server]
[server]    ErrorException
[server]
[server]   Undefined array key 1
[server]
[server]   at vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:368
[server]     364▕         $line = str_replace('  ', ' ', $line);
[server]     365▕
[server]     366▕         preg_match($regex, $line, $matches);
[server]     367▕
[server]   ➜ 368▕         return Carbon::createFromFormat('D M d H:i:s Y', $matches[1]);
[server]     369▕     }
[server]     370▕
[server]     371▕     /**
[server]     372▕      * Get the request port from the given PHP server output.
[server]
[server]   1   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:368
[server]       Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key 1", "C:\xampp 8_2_4\htdocs\ll11\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")
[server]
[server]   2   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:297
[server]       Illuminate\Foundation\Console\ServeCommand::getDateFromLine("[Wed Oct 16 10:42:32 2024] 127.0.0.1:50542 Accepted")
[server]
[server]
[server]    Whoops\Exception\ErrorException
[server]
[server]   Undefined array key 0
[server]
[server]   at vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:320
[server]     316▕                             microtime(true),
[server]     317▕                         ];
[server]     318▕                     }
[server]     319▕
[server]   ➜ 320▕                     [$startDate, $file, $startMicrotime] = $this->requestsPool[$requestPort];
[server]     321▕
[server]     322▕                     $formattedStartedAt = $startDate->format('Y-m-d H:i:s');
[server]     323▕
[server]     324▕                     unset($this->requestsPool[$requestPort]);
[server]
[server]   1   vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php:320
[server]       Whoops\Run::handleError("Undefined array key 0", "C:\xampp 8_2_4\htdocs\ll11\vendor\laravel\framework\src\Illuminate\Foundation\Console\ServeCommand.php")
[server]
[server]   2   vendor\laravel\framework\src\Illuminate\Collections\Traits\EnumeratesValues.php:257
[server]       Illuminate\Foundation\Console\ServeCommand::Illuminate\Foundation\Console\{closure}("[Wed Oct 16 10:42:33 2024] 127.0.0.1:50542 Closing")
[server]
[server] php artisan serve exited with code 1```

### Steps To Reproduce

1 install laravel v11.28
2 execute 2php artisan serve" or "composer run dev"
3 go to the browser with the local url 127.0.0.1:8000 
4 it crashed

**Comment by hafezdivandari** [comment]
Fixed on 11.28.1

**Comment by prajjwalupadhyay** [comment]
I also have this same error, and when I do "php artisan migrate", it gives the output of Illuminate\Database\QueryException : could not find driver and __construct(). 
![image](https://github.com/user-attachments/assets/a8656371-247c-497c-aad4-2496a0c6ce49)
Please, Can you help me by solving this error.

**Comment by hafezdivandari** [comment]
@prajjwalupadhyay @Zulf44 Laravel Pail requires `pcntl` PHP extension that is not supported on Windows. You may refer to laravel/pail#43

**Comment by Michael-King9812** [comment]
> Fixed on 11.28.1

am still getting same error message and I just cloned the laravel latest new project

**Comment by Michael-King9812** [comment]
am still getting the 

> Fixed on 11.28.1

am still getting the error message on Laravel Framework 11.36.1

**Comment by Guistoff081** [comment]
> Fixed on 11.28.1

Still happens on 11.38.2 

```bash
PS C:\Users\silva\Projects\estudos\chirper> composer run dev
> Composer\Config::disableProcessTimeout
> npx concurrently -c "#93c5fd,#c4b5fd,#fb7185,#fdba74" "php artisan serve" "php artisan queue:listen --tries=1" "php artisan pail --timeout=0" "npm run dev" --names=server,queue,logs,vite
[vite]       
[vite] > dev 
[vite] > vite
[vite]
[queue] 
[queue]    INFO  Processing jobs from the [default] queue.
[queue]
[logs]
[logs]    RuntimeException
[logs]
[logs]   The [pcntl] extension is required to run Pail.
[logs]
[logs]   at vendor\laravel\pail\src\Guards\EnsurePcntlIsAvailable.php:15
[logs]      11▕      */
[logs]      12▕     public static function check(): void
[logs]      13▕     {
[logs]      14▕         if (! function_exists('pcntl_fork')) {
[logs]   ➜  15▕             throw new RuntimeException('The [pcntl] extension is required to run Pail.');
[logs]      16▕         }
[logs]      17▕     }
[logs]      18▕ }
[logs]      19▕
[logs]
[logs]   1   vendor\laravel\pail\src\Console\Commands\PailCommand.php:46
[logs]       Laravel\Pail\Guards\EnsurePcntlIsAvailable::check()
[logs]
[logs]   2   vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
[logs]       Laravel\Pail\Console\Commands\PailCommand::handle(Object(Laravel\Pail\ProcessFactory))
[logs]
[logs] php artisan pail --timeout=0 exited with code 1
[vite] 
[vite]   VITE v6.0.7  ready in 446 ms
[vite]
[vite]   ➜  Local:   http://localhost:5173/
[vite]   ➜  Network: use --host to expose
[vite]
[vite]   LARAVEL v11.38.2  plugin v1.1.1
[vite]
[vite]   ➜  APP_URL: http://localhost
[server]   Failed to listen on 127.0.0.1:8000 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8001 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8002 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8003 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8004 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8005 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8006 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8007 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8008 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8009 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8010 (reason: ?)
[server] php artisan serve exited with code 1
Deseja finalizar o arquivo em lotes (S/N)? 
[vite] Deseja finalizar o arquivo em lotes (S/N)?
[queue] ^C
[queue] php artisan queue:listen --tries=1 exited with code 3221225786
Script npx concurrently -c "#93c5fd,#c4b5fd,#fb7185,#fdba74" "php artisan serve" "php artisan queue:listen --tries=1" "php artisan pail --t
Script npx concurrently -c "#93c5fd,#c4b5fd,#fb7185,#fdba74" "php artisan serve" "php artisan queue:listen --tries=1" "php artisan pail --timeout=0" "npm run dev" --names=server,queue,logs,vite handling the dev event returned with error code 1```

**Comment by tuliorubim** [comment]
I'm having the same error. It was told that the issue was fixed on version 11.28.1, but other users here have related that the same issue occurs on later versions. So what to do? If the issue is on Windows, should we migrate to Linux. If I use wsl, will I get rid of this server starting error?

**Comment by iLinkoDes** [comment]
Happened again on Laravel v12.7.2 :(
```
> npx concurrently -c "#93c5fd,#c4b5fd,#fdba74" "php artisan serve" "php artisan queue:listen --tries=1" "npm run dev" --names='server,queue,vite'
[vite]
[vite] > dev
[vite] > vite
[vite]
[queue]
[queue]    INFO  Processing jobs from the [default] queue.
[queue]
[server]   Failed to listen on 127.0.0.1:8000 (reason: ?)
[vite]
[vite]   VITE v6.2.0  ready in 648 ms
[vite]
[vite]   ➜  Local:   http://localhost:5173/
[vite]   ➜  Network: use --host to expose
[vite]
[vite]   LARAVEL v12.7.2  plugin v1.2.0
[vite]
[vite]   ➜  APP_URL: http://localhost
[server]   Failed to listen on 127.0.0.1:8001 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8002 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8003 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8004 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8005 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8006 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8007 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8008 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8009 (reason: ?)
[server]   Failed to listen on 127.0.0.1:8010 (reason: ?)
[server] php artisan serve exited with code 1
Terminate batch job (Y/N)?
[queue] ^C
[vite] Terminate batch job (Y/N)?
[queue] php artisan queue:listen --tries=1 exited with code 3221225786
Script npx concurrently -c "#93c5fd,#c4b5fd,#fdba74" "php artisan serve" "php artisan queue:listen --tries=1" "npm run dev" --names='server,queue,vite' handling the dev event returned with error code 1
```
