### ISSUE TITLE
Error in Laravel when inserting blank value in default blank NOT NULL field and when withoutMiddleware(ConvertEmptyStringsToNull::class) is also specified

### ISSUE THREAD

**Issue by nikunjbhatt** [laravel/framework#56955]
### Laravel Version

12.28.1

### PHP Version

8.2.0

### Database Driver & Version

MariaDB 10.11.9

### Description

Laravel seems changing blank values to null even if `withoutMiddleware(ConvertEmptyStringsToNull::class)` is specified on the route. Laravel is not allowing to insert empty string in the field on which default empty string is specified and NOT NULL is specified.

### Steps To Reproduce

As it requires many steps and changing code in multiple files, I have created a repository where everything is mentioned. Here is the URL to the repository: https://github.com/nikunjbhatt/Laravel-Error
Full description and steps to reproduce are provided in the README.md file in the repository.

I have also created a post in Laracasts forum, here is its link:
https://laracasts.com/discuss/channels/laravel/error-in-laravel-when-inserting-blank-value-in-default-blank-set-not-null-field-and-when-withoutmiddlewareconvertemptystringstonullclass-is-also-specified

**Comment by macropay-solutions** [comment]
We had a similar issue. Laravel considers empty string as valid and will not apply any validation on it. Wetter or not the field is returned as validated array from the validator you have to check but we fixed this for our projects. See [this](https://github.com/laravel/framework/issues/41734#issuecomment-3127680521).

But your issue is not the same. This is a laravel 11/12 issue only probably caused by the change in the way the app is bootstrapped. Can you try to remove the ConvertEmptyStringsToNull entirely from the whole app not only from your route?

Try

```php
->withMiddleware(function (Middleware $middleware) {
    $middleware->remove([
        ConvertEmptyStringsToNull::class,
        TrimStrings::class,
    ]);
})
```

**Comment by nikunjbhatt** [comment]
@macropay-solutions 
Where to put the code you provided?

**Comment by rodrigopedra** [comment]
> [@macropay-solutions](https://github.com/macropay-solutions) Where to put the code you provided?

On your project's `./bootstrap/app.php` file.

Reference: https://laravel.com/docs/12.x/middleware#global-middleware

**Comment by wizzymore** [comment]
Easier solution:
```php
$data = $request->validated([
    'name' => 'nullable|...',
    ...
]);
$data['name'] ??= '';

// Now use $data however you want as name is empty string
```

But the correct answer to your problem is that your design is wrong, if you want a non-value, like "No name" for the love of god use NULL as that is the default "NO VALUE" in a database, don't put an empty string. This also makes it easier to query for users with no names and you also denote to the other programmers or to yourself from the future that this column is not required.

**Comment by macropay-solutions** [comment]
> Easier solution:
> 
> $data = $request->validated([
>     'name' => 'nullable|...',
>     ...
> ]);
> $data['name'] ??= '';
> 
> // Now use $data however you want as name is empty string
> But the correct answer to your problem is that your design is wrong, if you want a non-value, like "No name" for the love of god use NULL as that is the default "NO VALUE" in a database, don't put an empty string. This also makes it easier to query for users with no names and you also denote to the other programmers or to yourself from the future that this column is not required.

@wizzymore  Hi. The way of the community is not always the best way. You opened that eager load [issue](https://github.com/laravel/framework/issues/56951) that the community considers an edge case but YOU (and us and others) need it. In the same way @nikunjbhatt needs this to work.

Converting empty string to null is just another opinionated decision, just like is that of considering empty strings always valid.

**Comment by macropay-solutions** [comment]
@rodrigopedra this is another example of opinionated architecture. You need to remove via code a middleware that the framework hardcoded so on each request that middleware is added then removed. In version <= 10 you just removed/commented a line of code and this adding and removing was avoided.

**Comment by nikunjbhatt** [comment]
@wizzymore 
> But the correct answer to your problem is that your design is wrong, if you want a non-value, like "No name" for the love of god use NULL as that is the default "NO VALUE" in a database, don't put an empty string. This also makes it easier to query for users with no names and you also denote to the other programmers or to yourself from the future that this column is not required.

As stated by @macropay-solutions , by default, replacing a blank value to something else (`null`) coming from the client and changing the data type to `null` is a bad practice in the first place. It must not be the default behavior in the framework. Instead a middleware should be provided explicitly to replace blank values to `null`. Still anyhow, if I specify `withoutMiddleware(ConvertEmptyStringsToNull::class)` on a route then Laravel must not convert blank values to `null`.

The following is working:
```php
$validated = $request->validate([
	'name' => 'max:255'
]);

$validated['name'] ??= '';
```

@macropay-solutions @rodrigopedra 
Your solution worked:
```php
$validated = $request->validate([
	'name' => 'string|max:255'
]);
```
Removed `withoutMiddleware(ConvertEmptyStringsToNull::class)` from the route.
Specified the following in the `\bootstrap\app.php`
```php
$middleware->remove([
	ConvertEmptyStringsToNull::class,
]);
```
... solved my issue.

**Comment by macropay-solutions** [comment]
@nikunjbhatt this can be closed with the conclusion that withoutMiddleware on route will remove only route middlewares not global middlewares.

**Comment by nikunjbhatt** [comment]
@macropay-solutions No. `withoutMiddleware()` on route isn't removing the specified middleware from the route. The problem/error still exist in Laravel framework. It is the title of this issue.

**Comment by wizzymore** [comment]
> [@macropay-solutions](https://github.com/macropay-solutions) No. `withoutMiddleware()` on route isn't removing the specified middleware from the route. The problem/error still exist in Laravel framework. It is the title of this issue.

That is not true at all, i recommend you read the documentation:
https://laravel.com/docs/12.x/middleware#excluding-middleware

> The withoutMiddleware method can only remove route middleware and does not apply to [global middleware](https://laravel.com/docs/12.x/middleware#global-middleware).

**Comment by nikunjbhatt** [comment]
@wizzymore You seems to be in very hurry. Please read my comment again until you understand it.

**Comment by wizzymore** [comment]
I think it's the other way around because you are fixed on this being a bug, which it is not.

Your example repo shows this on the route:
```php
Route::post('/', function (\Illuminate\Http\Request $request) {
	/*$validated = $request->validate([
		'name' => 'string|max:255'
	]);*/

	try {
		\App\Models\User::create($request->all());
	}
	catch (\Exception $e) {
		return back()->withErrors(['error' => $e->getMessage()]);
	}

	return redirect('/');
})->withoutMiddleware(ConvertEmptyStringsToNull::class);
```

Which currently does nothing, because `ConvertEmptyStringsToNull` it's a global middleware. You cannot remove a global middleware from the route level, you can only remove it globally from the `bootstrap/app.php` file as shown above:
```php
->withMiddleware(function (Middleware $middleware) {
    $middleware->remove([
        ConvertEmptyStringsToNull::class,
    ]);
})
```

If you to apply this middleware conditionally on routes you will need the following:
1. Remove it globally
```php
// boostrap/app.php
->withMiddleware(function (Middleware $middleware) {
    $middleware->remove([
        ConvertEmptyStringsToNull::class,
    ]);
})
```
2. Add it in a route group so it's easier to apply to multiple routes:
```php
// web.php

Route::middleware([ConvertEmptyStringsToNull::class])->group(function () {
    Route::get('/', function () {
        return view('welcome');
    });
});
```
3. If you want to have a route that doesn't include the middleware simply add the route outside the group:
```php
// boostrap/app.php
->withMiddleware(function (Middleware $middleware) {
    $middleware->remove([
        ConvertEmptyStringsToNull::class,
    ]);
})

.............

// web.php

Route::middleware([ConvertEmptyStringsToNull::class])->group(function () {
    Route::get('/', function () {
        return view('welcome');
    });
});

Route::post('/', function (\Illuminate\Http\Request $request) {
	/*$validated = $request->validate([
		'name' => 'string|max:255'
	]);*/

	try {
		\App\Models\User::create($request->all());
	}
	catch (\Exception $e) {
		return back()->withErrors(['error' => $e->getMessage()]);
	}

	return redirect('/');
});
```

The code snippets are from the code you provided when opening the issue.

Also, I recommend you from switching your condescending tone if you want any help in the future. I provided you with fixes, suggestions for more common patterns and shortcuts to documentation to help you out, you can take those in consideration or not, but saying `Please read my comment again until you understand it` it's immature

**Comment by macropay-solutions** [comment]
> [@macropay-solutions](https://github.com/macropay-solutions) No. `withoutMiddleware()` on route isn't removing the specified middleware from the route. The problem/error still exist in Laravel framework. It is the title of this issue.

@nikunjbhatt We said what @wizzymore detailed in his answer. You did not understood our reply:

>this can be closed with the conclusion that withoutMiddleware on route will remove only route middlewares not global middlewares.

**Comment by crynobone** [comment]
<img width="678" height="452" alt="Image" src="https://github.com/user-attachments/assets/60b68d40-5428-48ae-b8af-991fe6de6ca6" />

You can use above suggestion or 

```php
->withMiddleware(function (Middleware $middleware): void {
    $middleware->convertEmptyStringsToNull([
        fn () => false, // disable globally
        fn ($request) => $request->scheme() === 'https', // determine based on Request object
     ]);
 });
```

**Comment by nikunjbhatt** [comment]
@wizzymore @macropay-solutions @crynobone 
Forget about global middleware; it seems working fine, I have no problem with it.

What you people are not understanding is `withoutMiddleware(ConvertEmptyStringsToNull::class)` is not working when specified on a route:
```php
Route::post('/', function (Request $request) {
// some code here
})->withoutMiddleware(ConvertEmptyStringsToNull::class);
```
The above is not working. I am still getting `null` value instead of blank value. Is it how it is supposed to work? Shouldn't `withoutMiddleware(ConvertEmptyStringsToNull::class)` on the route stop converting blank values to nulls? Shouldn't this be called a bug? If specifying `withoutMiddleware(ConvertEmptyStringsToNull::class)` on a route does nothing then why is it there? Why any error is not occurring?

**Comment by macropay-solutions** [comment]
> Is it how it is supposed to work? Shouldn't withoutMiddleware(ConvertEmptyStringsToNull::class) on the route stop converting blank values to nulls? Shouldn't this be called a bug? If specifying withoutMiddleware(ConvertEmptyStringsToNull::class) on a route does nothing then why is it there? Why any error is not occurring?

Acc to documentation this is how it should work. We all told you that **it has no effect on global middlewares**. It only removes routes middlewares.

**Comment by nikunjbhatt** [comment]
@macropay-solutions You are still stuck with the global middleware; I have told you to forget it.

Let me show you an example.

Here is the code of the `\resources\views\welcome.blade.php`:
```html
<form method="POST" action="/">
	@csrf
	<p>Name: <input name="name" placeholder="Enter blank value and submit"></p>
	<p><button>Submit</button></p>
</form>
```

Here is the code of the route in `web.php`:
```php
Route::post('/', function (Request $request) {
	if($request->name === null)
		\Log::info('name is null');
	elseif($request->name === '')
		\Log::info('name is empty/blank');
	else
		\Log::info('name is ' . $request->name);
})->withoutMiddleware(ConvertEmptyStringsToNull::class);
```
What will be logged in the `laravel.log` file if I submit the form without inputting anything in `name`'s textbox?

**Comment by macropay-solutions** [comment]
@nikunjbhatt we understand what you want to say but Laravel team has a different (opinionated) opinion about this. If you want the old Laravel 10 way of doing things, there are maintained alternatives to it.

**Comment by rodrigopedra** [comment]
@nikunjbhatt on your `./bootstrap/app.php` file use this:

```php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;
use Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull;
use Illuminate\Foundation\Http\Middleware\TrimStrings;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {
        $middleware->remove(TrimStrings::class);
        $middleware->remove(ConvertEmptyStringsToNull::class);
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })->create();
```

The `Illuminate\Foundation\Configuration\Middleware@remove` method will remove the middleware from the global stack.

If you want to completely customize your app's global stack, you can use the `Illuminate\Foundation\Configuration\Middleware@use` method:

```php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {
        $middleware->use([
            Illuminate\Http\Middleware\ValidatePathEncoding::class,
            Illuminate\Foundation\Http\Middleware\InvokeDeferredCallbacks::class,
            // Illuminate\Http\Middleware\TrustHosts::class,
            Illuminate\Http\Middleware\TrustProxies::class,
            Illuminate\Http\Middleware\HandleCors::class,
            Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::class,
            Illuminate\Http\Middleware\ValidatePostSize::class,
            // Illuminate\Foundation\Http\Middleware\TrimStrings::class,
            // Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })->create();
```

Mind that if you pass an empty array to the `Illuminate\Foundation\Configuration\Middleware@use` method, it will be replaced by the default global stack as defined here:

https://github.com/laravel/framework/blob/3be63bb8183b60224a4b7d094b3c3559802314d0/src/Illuminate/Foundation/Configuration/Middleware.php#L453-L463

That is due to the short-ternary operator (`?:`) being used to verify if the global middleware stack had already been defined.

If you want a complete empty global middleware stack, for whatever reason, you can either remove each default middleware using the `Illuminate\Foundation\Configuration\Middleware@remove` method, or create a dummy middleware that does nothing and set that as the sole middleware in the global stack.

Something like this:

```console
$ php artisan make:middleware Dummy
```

Then in your `./bootstrap/app.php` file:

```php
<?php

use Illuminate\Foundation\Application;
use Illuminate\Foundation\Configuration\Exceptions;
use Illuminate\Foundation\Configuration\Middleware;

return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withMiddleware(function (Middleware $middleware): void {
        $middleware->use([
            App\Http\Middleware\Dummy::class,
        ]);
    })
    ->withExceptions(function (Exceptions $exceptions): void {
        //
    })->create();
```

**Comment by macropay-solutions** [comment]
@rodrigopedra at least you can overwrite the global defaults. Good to know.

This should be the default in the template

```php

    ->withMiddleware(function (Middleware $middleware): void {
        $middleware->use([
            Illuminate\Http\Middleware\ValidatePathEncoding::class,
            Illuminate\Foundation\Http\Middleware\InvokeDeferredCallbacks::class,
            // Illuminate\Http\Middleware\TrustHosts::class,
            Illuminate\Http\Middleware\TrustProxies::class,
            Illuminate\Http\Middleware\HandleCors::class,
            Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance::class,
            Illuminate\Http\Middleware\ValidatePostSize::class,
            // Illuminate\Foundation\Http\Middleware\TrimStrings::class,
            // Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        ]);
    })
```

**Comment by nikunjbhatt** [comment]
Removal of `ConvertEmptyStringsToNull` is working if it is removed through `\bootstrap\app.php`, but it doesn't work if specified for removal on a route or route group. But now I am facing a reverse problem. For the `VerifyCsrfToken`, exactly opposite is happening. If I remove the middleware `VerifyCsrfToken` through the `\bootstrap\app.php` as following:
```php
->withMiddleware(function (Middleware $middleware): void {
	$middleware->remove([
		VerifyCsrfToken::class,
	]);
})
```
then it is not working. Laravel is responding with the HTTP error `419 Page Expired` in response to a post request when `@csrf` is not specified in the form.

However, if I remove the `VerifyCsrfToken` middleware from routes' group or a route then it is working!
```php
Route::withoutMiddleware(VerifyCsrfToken::class)->group(function() {
	Route::post('/submit', [MyController::class, 'submit'])->name('submit');
});
```
Or
```php
Route::post('/submit', [MyController::class, 'submit'])->name('submit')->withoutMiddleware(VerifyCsrfToken::class);
```
Is there any "standard" in Laravel about which middleware removal works where/how?

**Comment by macropay-solutions** [comment]
@nikunjbhatt VerifyCsrfToken is a route middleware applied only on the web routes not in the api routes nor in global routes.

**Comment by nikunjbhatt** [comment]
@macropay-solutions the `/submit` route is in `web.php` route file, it is not an API route. So, specifying 
```php
->withMiddleware(function (Middleware $middleware): void {
	$middleware->remove([
		VerifyCsrfToken::class,
	]);
})
```
should work on all routes in `web.php`, but it is not working.

And, my questions are - is there any list mentioning all the middlewares, which middleware can be added to or removed from which files, and which middleware is applicable to what kind of route (`web.php`/`api.php`)?

**Comment by rodrigopedra** [comment]
@nikunjbhatt `$middleware->remove(...)` will remove a middleware from the global stack.

The `VerifyCsrfToken` middleware is not applied to the global stack by default.

To remove a middleware from a middleware group, such as `web`, you can use:

```php
$middleware->removeFromGroup('web', VerifyCsrfToken::class);
```

Or, as `web` is a default middleware group, use the `$middleware->web()` shorthand, as said in the docs:

```php
$middleware->web(remove: [
    VerifyCsrfToken::class,
]);
```

Reference: https://laravel.com/docs/12.x/middleware#laravels-default-middleware-groups
