### ISSUE TITLE
[Eloquent] Relations doesn't use connection of parent model.

### ISSUE THREAD

**Issue by deftomat** [laravel/framework#9355]
I try to get models with their relation from connection, which is chosen dynamically:

```php
User::on('another-db')->with('article')->get();
```

Unfortunately, instance of related model, which is created in the ```Model::hasMany()``` function does not contain this connection.

Solution is to modify function as follows:

```php
public function hasMany($related, $foreignKey = null, $localKey = null)
{
    $foreignKey = $foreignKey ?: $this->getForeignKey();

    $instance = new $related;

    // FIX
    if ($instance->getConnection() == null)  {
        $instance->setConnection($this->connection);
    }

    $localKey = $localKey ?: $this->getKeyName();

    return new HasMany($instance->newQuery(), $this, $instance->getTable().'.'.$foreignKey, $localKey);
 }
```

This solution may be used also in ```belongsTo()```, ```belongsToMany()```, etc.

I can create the pull request, but I think this solution may be undesirable if the user wants to define the relation between the parent model from *another-db* connection and the related model from *default* connection. This solution override a *default* connection in related model.

However, I believe that relations between models from the same database are more likely than relations between models from different databases.

**Comment by GrahamCampbell** [comment]
What laravel version?

**Comment by deftomat** [comment]
I try it with ```5.1.2``` and also with ```4.1.*```

**Comment by WazzaJB** [comment]
I am also experiencing this issue, I know this is not intended behaviour as [Eloquent/Model.php Line 614](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Database/Eloquent/Model.php#L614) states:

```
// First we will just create a fresh instance of this model, and then we can
// set the connection on the model so that it is be used for the queries
// we execute, as well as being set on each relationship we retrieve.
```

**Comment by jorgercosta** [comment]
Also looking for fix for this

**Comment by BrettTrotter** [comment]
Also just ran into this. 4.1

**Comment by GrahamCampbell** [comment]
> Also just ran into this. 4.1

4.1 is not supported.

**Comment by GrahamCampbell** [comment]
@deftomat That fix you provide looks wrong to me.

**Comment by GrahamCampbell** [comment]
> I am also experiencing this issue, I know this is not intended behaviour as Eloquent/Model.php Line 614 states:

That is for the on method, not for relationa.

**Comment by GrahamCampbell** [comment]
Each model defines it's own connection, and does not try to use that of another model. If you want this behaviour, you need to roll your own relation functions.

**Comment by WazzaJB** [comment]
Although probably not the best solution to this issue, I did manage to come up with a workaround.

Store the current database, then set the current database to be the database of the relation.
```
$default = Config::get('database.default');
Config::set('database.default', 'mysql_master');
```

After you've done your query, reset the current database in current config.

```
Config::set('database.default', $default);
```

Hope this helps anyone with a similar issue.

**Comment by liladani** [comment]
For those who still has this problem:

```php
function relation(){
   $foreignKey = 'fKey';
   $localKey  = 'lKey';
   
   $instance = new Model();
   $instance->setConnection($this->getConnectionName());

  return new HasOne($instance->newQuery(), $this, $instance->getTable().'.'.$foreignKey, $localKey);
}
```

I hope it helps!

**Comment by liladani** [comment]
Of course you will have to adapt that to suit your type of relation.... 
This should work with eager loading too.... 
but I still think it would be great to have a documented final solution to this.

**Comment by ctrlaltdylan** [comment]
Would be great if:

`$modelInstance->setConnection('different-database')->relation()->first();`

Was possible.

**Comment by davisonja** [comment]
I've just run into this with 5.1 also.

Instead of duplicating the wheel by rolling-your-own relation functions I suggest a method of specifying that related models should inherit (or the parent should propogate, given it seems the appropriate place for the change is in Model.php) the parent's connection. The likes of a 'propogateConnection' flag which is used in belongsTo (etc):

```php
$instance = new $related;
if ($this->propogateConnection) {
    $instance->setConnection($this->getConnectionName());
}
```

**Comment by Frondor** [comment]
Why is it closed? Model relationships aren't inheriting parent's connections, we aren't able to set a connection for them neither

**Comment by tannermccoleman** [comment]
If model relationships with pivot tables don't inherit a connection shared by both related models, there should at least be a way to set the pivot table or connection dynamically.

**Comment by manu144x** [comment]
I did a completely unorthodox way,  I needed an extremely urgent fix, and since this hasn't been updated for 2 years I just added this line in the Model.php on all the relationship functions:

```
$instance = new $related;
$instance->setConnection($this->getConnectionName());
```

And it just works as expected absolutely everywhere, if there is no connection overload, it just uses the default one and that's it.

I think it should be the official fix, but until then I had to commit the Laravel framework folder to my repository, and lock the version in composer. 

I hope an official fix will soon arise so I don't have to do these kinds of blasphemy.

**Comment by ctrlaltdylan** [comment]
@manu144x sometimes the unorthodox solutions are the best solutions!

**Comment by reno1979** [comment]
I also encountered this issue in 5.3.19 :( 

I hope there will be a real fix for this

**Comment by reno1979** [comment]
@GrahamCampbell @taylorotwell @themsaid @BartHuis  

Could this issue please be reopend? 
I've encounter multiple issues this week, all caused by this underlying mecanism/issue. 

I 'solved' it with changing the default database connection and restoring it, but this is going to introduce unwanted effects eventually. 

Adding this 'fix' to relations in a own made model should work:

```
$instance = new $related;
$instance->setConnection($this->getConnectionName());
``` 
When a Laravel extension (which creates relations in your Models etc) is used, this extension should also apply this 'fix'. :( 

But a real solution would be much nicer. I saw a proposal for a propegateConnection by @davisonja 
Something like that could work. Or similar: 

```
App\myModel::on('mysql2', true); /* True for propegate connection */
```

**Comment by themsaid** [comment]
@reno1979 it's not a bug, it's by design.

**Comment by BartHuis** [comment]
@themsaid and how do you have to work around in our case?

**Comment by BartHuis** [comment]
@themsaid becouse when you set the connection, and the script fails, your connection stays on the wrong one.

**Comment by BartHuis** [comment]
would be nice, would be a solution for this one also then: https://github.com/dimsav/laravel-translatable/issues/283

**Comment by avasa** [comment]
I had the same issue when relationship wasn't working off the parent connection.

My solution was to override the belongsToMany method on the model trying to establish . See example below.

`<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class ConnectionModel extends Model
{
    /**
     * Override method to allow inheriting connection of parent
     *
     * Define a many-to-many relationship.
     *
     * @param  string  $related
     * @param  string  $table
     * @param  string  $foreignKey
     * @param  string  $otherKey
     * @param  string  $relation
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany|BelongsToMany
     */
    public function belongsToMany($related, $table = null, $foreignKey = null, $otherKey = null, $relation = null)
    {
        // If no relationship name was passed, we will pull backtraces to get the
        // name of the calling function. We will use that function name as the
        // title of this relation since that is a great convention to apply.
        if (is_null($relation)) {
            $relation = $this->getBelongsToManyCaller();
        }

        // First, we'll need to determine the foreign key and "other key" for the
        // relationship. Once we have determined the keys we'll make the query
        // instances as well as the relationship instances we need for this.
        $foreignKey = $foreignKey ?: $this->getForeignKey();

        $instance = new $related;

        $instance->setConnection(parent::getConnectionName());

        $otherKey = $otherKey ?: $instance->getForeignKey();

        // If no table name was provided, we can guess it by concatenating the two
        // models using underscores in alphabetical order. The two model names
        // are transformed to snake case from their default CamelCase also.
        if (is_null($table)) {
            $table = $this->joiningTable($related);
        }

        // Now we're ready to create a new query builder for the related model and
        // the relationship instances for the relation. The relations will set
        // appropriate query constraint and entirely manages the hydrations.
        $query = $instance->newQuery();

        return new BelongsToMany($query, $this, $table, $foreignKey, $otherKey, $relation);
    }
}`

**Comment by BartHuis** [comment]
@avasa I didn't read everything yet, but do you use the most recent laravel version? Much things are already fixed...

**Comment by Frondor** [comment]
This is already implemented on L5.4, although I think it should be optional by setting something like `protected $inheritConnection = true;` because its annoying to handle some times.

**Comment by avasa** [comment]
@BartHuis @Frondor I am currently using version 5.2. I will try and update my package.  Appriciated the feedback guys.

**Comment by fredec** [comment]
I could solve with the 1st answer in here: https://laracasts.com/discuss/channels/general-discussion/join-query-with-another-database-connection-model

**Comment by JRogaishio** [comment]
Sorry to revive a crazy old issue but this still happens in laravel 5.8-7.x.

I've found a possible solution which involves overwriting `Illuminate/Database/Eloquent/Concerns/HasRelationships.php` `newRelatedInstance()` method. This can be done in your base model and seems fairly easy.
https://github.com/laravel/ideas/issues/2326
